### PR TITLE
Hbz lobid rdf to json 26 simple strings for types

### LINKED ISSUE #26: Use simple strings for types, mapped to URI in context
This means we will have to define the terms in the JSON-LD context.

From https://github.com/hbz/lobid-resources/issues/9#issuecomment-174461204. See also https://github.com/hbz/lobid-resources/issues/10#issuecomment-174447850 f.

### PR DESCRIPTION
**Pull request by dr0i**
Will help to resolve #26.

### CODE REVIEW

**Comment by jschnasse** [comment]
new file  src/test/resources/u still contains uris as types

**Comment by jschnasse** [comment]
maybe a test file with all existing types would make sense in order to test if all lobid-types are properly supported by current labels.json?

**Comment by dr0i** [comment]
Ah - good catch :) The json resource " src/test/resources/u" was accidentially introduced. Removed it in new commit ffb6f17d83dc8536bc7187cec12fad89594755ff.
( In principle, types are pretty well tested I think, also in the hbz/lobid-resources repo.)

**Comment by jschnasse** [comment]
+1

**Pull request merged**
