### PR TITLE
Add missing labels

### LINKED ISSUE #30: Implement side car approach
Using "label" mapped to rdfs:label. For GND resources the labels are taken from the data, for others (e.g. medium) we will use Etikett.

Example:

``` javascript
{
    "@context":{
        "id": "@id",
       "type": "@type",
       "label":"http://www.w3.org/2000/01/rdf-schema#label",
       "subject":{
          "@id":"http://purl.org/dc/terms/subject",
          "@type":"@id"
       },
       "Book": "http://purl.org/ontology/bibo/Book",
       "Thesis": "http://purl.org/ontology/bibo/Thesis"
    },
    "id":"http://lobid.org/resources/HT018881872#!",
    "type":[ "Book", "Thesis" ],
    "medium" : [ {
      "id": "http://rdvocab.info/termList/RDAproductionMethod/1010",
      "label": "Print"
      }
    ],
    "title":[
       "Skateboarding"
    ],
    "otherTitleInformation":[
       "Ethnographie einer urbanen Praxis"
    ],
    "creator":[
       {
          "id":"http://d-nb.info/gnd/103058788",
          "label":"Peters, Christian"
       }
    ],
    "subject":[
       {
          "id":"http://d-nb.info/gnd/4181628-6",
          "label":"Skateboardfahren"
       },
       {
          "id":"http://d-nb.info/gnd/4031483-2",
          "label":"Köln"
       }
    ]
}
```

### PR DESCRIPTION
**Pull request by acka47**
Fixes #30. This doesn't add medium information but we have to discuss this anyway.

### CODE REVIEW

**Comment by dr0i** [comment]
Hi @jschnasse maybe you would like to review the test classes.

**Review by dr0i — COMMENTED** [review]
The [updated README](https://github.com/hbz/lobid-rdf-to-json/pull/56/files/f97e011e2a5f9ea7f4df65e805eb01366e00ea55?short_path=8aa641a#diff-8aa641a619b8ebeca0116d41774daf45) is especially important for @acka47, please acknowledge.

**Comment by acka47** [comment]
+1 I understand the README.

**Comment by jschnasse** [comment]
Ok test the test.
The following experiment brings some unexpected results. But why?:

```
git checkout 30-addMissingLabels
mvn test #succeeds
```

ok - like expected. What happens if I change labels.json back

```
git checkout master src/main/resources/labels.json
mvn test #fails
git status
```

ok, some files in output/json changed

```
 mvn test #still fails
 git status
```

hm - it still fails, and modifies some additional files in reverseTest/output

```
mvn test #still fails
```

Try to revert

```
git reset src/main/resources/labels.json
git checkout src/main/resources/labels.json
mvn test #still fails
git status
```

ok, output/json files are converted back. reverseTest/output is still modified

```
mvn test #now succeeds
git status
```

 reverseTest/output is still modified

**Comment by jschnasse** [comment]
Hi @droi, I'd suggest to refactor the code so that, 
- one can trigger generation of testfiles with an additional command, e.g. using Maven exec plugin 
  
  mvn exec:java -Dexec.mainClass="de.hbz.lobid.helper.GenerateTestData"
- mvn test leaves data unmodified

**Comment by dr0i** [comment]
Hi @jschnasse re:"test the test": there was indeed a bug while updating files, see 0c8cd5a4c901cef2ee9f11a62be57f81e85ddde1 for the fix. Thx for catching the bug!

If you would run your "meta"-test again: you are expected to repeat "mvn test" so often till it suceed at the end ("mvn test --fail-at-end" can speed this up but ->). This is not really nice I admit, and ACK to implement a trigger resulting in all test files updated at once.

**Comment by dr0i** [comment]
@jschnasse Please have a look again. I separated the test and test data generation: "mvn test" should work as normal while "mvn test -DgenerateTestData=true" would write the generated new data into the filesystem.

**Comment by jschnasse** [comment]
+1

**Pull request merged**
