### PR TITLE
Add simple strings for types, mapped to URI in labels/context

### LINKED ISSUE #26: Use simple strings for types, mapped to URI in context
This means we will have to define the terms in the JSON-LD context.

From https://github.com/hbz/lobid-resources/issues/9#issuecomment-174461204. See also https://github.com/hbz/lobid-resources/issues/10#issuecomment-174447850 f.

### PR DESCRIPTION
**Pull request by dr0i**
Will fix #26.
Ommited labels for now.

### CODE REVIEW

**Comment by acka47** [comment]
I just noticed that I didn't add `MultiVolumeWorkRelation` and `SeriesRelation` from lobid vocab to the list. I will push them to this branch tomorrow.

**Comment by jschnasse** [comment]
@acka47 please add the missing properties to labels.json. From now on the context.json is generated from labels.json, see https://github.com/hbz/lobid-rdf-to-json/pull/41/commits/75baec52493d62611d9df2a3717072fd81f43a50

**Comment by jschnasse** [comment]
@acka47 and @dr0i 
1. I'd suggest to exclude the generated context.json from versioning, because it is only generated from labels.json. 
2. I'm not convinced that this repo is the right place to maintain your context. In my own tool chain the context is a product of an extensive 'application profile' that is maintained and continuously extended through an installed instance of etikett. I'd suggest to use this setup for lobid too, and install an etikett instance on one of your servers.  That would lead to the following work flow:
- add an entry to etikett database
- update the new labels.json to lobid-rdf-to-json
- update the context.json on your server (you can use the version of your etikett instance or a generated instance from this repo)

**Comment by dr0i** [comment]
Re comments from @jschnasse : I made new issues for these suggestions: #42 and #43.

**Comment by dr0i** [comment]
@acka47 after updating this branch to the new master, please have a look at the diff.

**Comment by jschnasse** [comment]
I'm very sure lables are optional fields. You don't have to provide something like "label":"dummy" .

**Comment by acka47** [comment]
+1

**Pull request merged**
