### PR TITLE
update Etikett model to new etikett version

### PR DESCRIPTION
**Pull request by jschnasse**
- transform former labels.json into new version
- example etikett with multilang container.
  [ {
  "uri" : "http://aims.fao.org/aos/agrovoc/c_10175",
  "label" : "Erntegutlagerung",
  "multilangLabel" : {
    "de" : "Erntegutlagerung",
    "hi" : "फसल भण्डारण",
    "ru" : "хранение урожая",
    "lo" : "ການເກັບຮັກສາພືດຜົນ",
    "pt" : "Armazenamento das colheitas",
    "ko" : "작물저장",
    "en" : "crop storage",
    "it" : "Immagazzinamento dei raccolti",
    "fr" : "Stockage des récoltes",
    "hu" : "termés raktározása",
    "zh" : "收获储藏",
    "cs" : "skladování plodin",
    "th" : "การเก็บรักษาพืชผล",
    "ja" : "作物貯蔵",
    "sk" : "skladovanie plodín",
    "fa" : "ذخيره‌سازي محصولات زراعی",
    "pl" : "Magazynowanie ziemiopłodów",
    "tr" : "ürün depolama"
  }
  } ]
- the multilangLabel object can be included directly into
  json-ld. Simply set the container type to @language to support
  rdf conversion. Example conversion for a field prefLabel.

http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "skladov\u00E1n\u00ED plodin"@cs .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "Erntegutlagerung"@de .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "crop storage"@en .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "\u0630\u062E\u064A\u0631\u0647\u200C\u0633\u0627\u0632\u064A \u0645\u062D\u0635\u0648\u0644\u0627\u062A \u0632\u0631\u0627\u0639\u06CC"@fa .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "Stockage des r\u00E9coltes"@fr .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "\u092B\u0938\u0932 \u092D\u0923\u094D\u0921\u093E\u0930\u0923"@hi .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "term\u00E9s rakt\u00E1roz\u00E1sa"@hu .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "Immagazzinamento dei raccolti"@it .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "\u4F5C\u7269\u8CAF\u8535"@ja .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "\uC791\uBB3C\uC800\uC7A5"@ko .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "\u0E81\u0EB2\u0E99\u0EC0\u0E81\u0EB1\u0E9A\u0EAE\u0EB1\u0E81\u0EAA\u0EB2\u0E9E\u0EB7\u0E94\u0E9C\u0EBB\u0E99"@lo .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "Magazynowanie ziemiop\u0142od\u00F3w"@pl .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "Armazenamento das colheitas"@pt .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "\u0445\u0440\u0430\u043D\u0435\u043D\u0438\u0435 \u0443\u0440\u043E\u0436\u0430\u044F"@ru .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "skladovanie plod\u00EDn"@sk .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "\u0E01\u0E32\u0E23\u0E40\u0E01\u0E47\u0E1A\u0E23\u0E31\u0E01\u0E29\u0E32\u0E1E\u0E37\u0E0A\u0E1C\u0E25"@th .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "\u6536\u83B7\u50A8\u85CF"@zh .
http://aims.fao.org/aos/agrovoc/c_10175 http://www.w3.org/2004/02/skos/core#prefLabel "\u00FCr\u00FCn depolama"@tr .

### CODE REVIEW

**Comment by dr0i** [comment]
Could you provide a test? This would also make it clear how this works and what it does.

**Comment by jschnasse** [comment]
This PR aims to update labels format to the one provided by current etikett instance - see last commit 8615ecf50c8  . Ouch - with old etikett model it will fail. But wait, let me fix it:

**Comment by jschnasse** [comment]
yes! now - after 56c0536e7530 - we can use current etikett instance to update our labels.conf.

**Comment by jschnasse** [comment]
Huh - the rdf language @'s . Sent notification messages to github users.

**Comment by dr0i** [comment]
In the meantime I think I got the idea - an Object-URI, if configured in lables.json, can now be expanded into multiple language prefLabel statements.
Would be also nice for dewey :)
+1

**Comment by jschnasse** [comment]
exactly. I don't think it will work out of the box but the converter is now prepared to work on multilang labels.

**Pull request merged**
