### PR TITLE
apply current lobid context to test data 

### PR DESCRIPTION
**Pull request by jschnasse**
- adds support for embedded and linked context
- creates testdata with linked context
- fixes failures in labels.json and context.json
- \- isPartOf - contributorOrder 
- adds missing fields to context
- \- frequency , etc.

### CODE REVIEW

**Comment by jschnasse** [comment]
Hi @dr0i  , please merge if you are happy with the current status. @acka47 will review after merge and post issues on open topics. the current PR changes the context.json so that reviewing the older context is not longer sensible, since I had to apply some changes during my last commits.

**Comment by dr0i** [comment]
The new context.json lacks 10 lines. Just trying to figure out why.

**Comment by jschnasse** [comment]
mabe you can throw it to your jsoncomparer

**Comment by dr0i** [comment]
> mabe you can throw it to your jsoncomparer

Yes indeed - works like a charm :) (had to fix some issues, though, and will make it runnable from cli)

**Pull request merged**
