### PR TITLE
74 agents still arrays

### LINKED ISSUE #74: Agents without GND ID are still arrays
Moved from https://github.com/hbz/lobid-rdf-to-json/pull/68#issuecomment-270338122:

> Sometimes agent still has an array, see e.g. http://lobid.org/resources/HT017632125#! or http://test.lobid.org/resources/TT050244740. Looks like this is the case for all agents without GND ID.

hbz/lobid-resources#132 depends on this.

### PR DESCRIPTION
**Pull request by dr0i**
Fixes #74.

### CODE REVIEW

**Comment by acka47** [comment]
This isn't deployed to staging yet, is it?

**Comment by dr0i** [comment]
right, not yet

**Comment by ChristophEwertowski** [comment]
Agents are not arrays anymore but if http://rdvocab.info/termList/RDAproductionMethod/#1010 is added it would be good if http://rdvocab.info/termList/RDAproductionMethod/1010 is removed. Depends on (#74)[https://github.com/hbz/lobid-resources/issues/74].

**Comment by dr0i** [comment]
Re: `rda:1010` :
I think you mixed this up with the other's repo issue. It's not part of of the "agent"-issue.

**Comment by ChristophEwertowski** [comment]
You are right, I mistook it for the lobid-resources issue.

**Comment by dr0i** [comment]
Deployed to staging. See e.g. http://test.lobid.org/resources/TT050244740.

**Comment by acka47** [comment]
+1

**Comment by fsteeg** [comment]
+1

**Comment by dr0i** [comment]
Deployed to production.

**Pull request merged**
