### PR TITLE
Sync json context json lobid json context

### PR DESCRIPTION
**Pull request by dr0i**
- add labels when missing
- remove unneeded entries

### CODE REVIEW

**Comment by dr0i** [comment]
@acka47 Would be nice if you could review this context. Feel free to change anything! Be aware, though, that the fieldnames should be as they are because these are used in the API logik. But change the `labels` at your will!
(This file will be included into http://aither.hbz-nrw.de:9000/tools/etikett to make a label.json which is needed for the mapping ntriples->Json-LD_with_context.)

**Comment by acka47** [comment]
I am ok with shortening the document by removing some lines of comments. @dr0i , please go ahead: merge and deploy.

**Comment by acka47** [comment]
I will check the labels. But I won't check whether all properties from the [production context](https://github.com/hbz/lobid/blob/master/conf/contexts/lobid-resources.json) are covered and the same field names are used as I hope that you covered this.

**Comment by acka47** [comment]
As written by @jschnasse at https://github.com/hbz/lobid-rdf-to-json/pull/7#issuecomment-161954446 I will rather review input and output data as well as labels and context as soon as #7 is merged.

**Pull request merged**
